server:
  port: 8085

spring:
  application:
    name: reconciliation-service
  
  datasource:
    url: jdbc:mysql://localhost:3307/distribute_bank?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  redis:
    host: localhost
    port: 6379
    database: 0

logging:
  level:
    com.distributebank: DEBUG 